package com.uep.followmymoney.domain;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CUENTA".
 */
@Entity
public class Cuenta {

    @Id
    private Long id;

    @NotNull
    private String nombre;
    private String descripcion;
    private java.util.Date fechaCreacion;

    @Convert(converter = com.uep.followmymoney.domain.TipoCuentaConverter.class, columnType = Integer.class)
    private TipoCuenta tipo;

    @Generated(hash = 1759493803)
    public Cuenta() {
    }

    public Cuenta(Long id) {
        this.id = id;
    }

    @Generated(hash = 971612538)
    public Cuenta(Long id, @NotNull String nombre, String descripcion, java.util.Date fechaCreacion,
            TipoCuenta tipo) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fechaCreacion = fechaCreacion;
        this.tipo = tipo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(@NotNull String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public java.util.Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(java.util.Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public TipoCuenta getTipo() {
        return tipo;
    }

    public void setTipo(TipoCuenta tipo) {
        this.tipo = tipo;
    }

}
